### ISSUE TITLE
Broken avatar searching.

### ISSUE THREAD

**Issue by Nuthrixon** [realseal5/EmmVRC-Melonloader-Autoinstaller-for-VRChat#3]
I keep trying to reinstall EMMVRC, but the avatar searching is completely gone. I have the searched-favorited avatars still, but the ones I did not favorite are gone now. Please fix the avatar search area!

**Comment by realseal5** [comment]
I'm sorry but i'm not affiliated with EmmVRC nor have I anything to do with it's development. This tool is only there to install Melonloader and EmmVRC. So if you have any problems with the mod you should go to https://emmvrc.com/ or their discord Server.

Kind Regards
realseal5

**Comment by Nuthrixon** [comment]
Ah, thank you.
